### ISSUE TITLE
Cache Everything

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/github-action#2]
Cache compiler binaries stored in `~/.vvm` and `~/.solcx`, also try to cache user's `.build/` folder that contains their compiled contracts so it doesn't do it again between sessions/steps in workflow.

example: https://github.com/yearn/yearn-vaults/blob/main/.github/workflows/test.yaml

**Comment by sabotagebeats** [comment]
these should be moved into github-action

**Comment by fubuloubu** [comment]
> these should be moved into github-action

Yes! My point is that when using this action (or perhaps even the docker container in general) it should be able to cache these folders quite easily (perhaps by letting you use them in the docker container), so you don't have to implement these features (which almost everyone will want) independently in each project that uses this action.

**Comment by fubuloubu** [comment]
solved by #4
