### ISSUE TITLE
`Path Validation Error` in Post Setup Ape [APE-1158]

### ISSUE THREAD

**Issue by pcaversaccio** [ApeWorX/github-action#23]
For replication, see [this](https://github.com/pcaversaccio/snekmate/actions/runs/5430063261/jobs/9875534341) run and go to the section `Post Setup Ape`

```bash
Post job cleanup.
Post job cleanup.
Cache hit occurred on the primary key [3](https://github.com/pcaversaccio/snekmate/actions/runs/5430063261/jobs/9875534341#step:30:3).11-pip-, not saving cache.
Post job cleanup.
Post job cleanup.
Cache hit occurred on the primary key Linux-build-cache, not saving cache.
Post job cleanup.
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

**Comment by antazoey** [comment]
I have also noticed this.

**Comment by antazoey** [comment]
Unfortunately the GitHub cache action requires archives to exist if you say you want to cache them. In our case:

1. the .build won't exist if you are not compiling
2. the .vvm won't exist if you are not using vyper
3. the .solc won't exist if you are not using solc

There is no setting (yet) in the action to allow empty.
Related issue: https://github.com/actions/cache/issues/1241

I have a workaround in place that creates empty directories if they do not exist (see attached PR).

**Comment by pcaversaccio** [comment]
> Unfortunately the GitHub cache action requires archives to exist if you say you want to cache them. In our case:
> 
> 1. the .build won't exist if you are not compiling
> 2. the .vvm won't exist if you are not using vyper
> 3. the .solc won't exist if you are not using solc
> 
> There is no setting (yet) in the action to allow empty. Related issue: [actions/cache#1241](https://github.com/actions/cache/issues/1241)
> 
> I have a workaround in place that creates empty directories if they do not exist (see #27).

Thanks for fixing, but I'm not sure I can fully follow. In my case, for example, I'm using ape vyper compilation [here](https://github.com/pcaversaccio/snekmate/actions/runs/7755119989/job/21149836621#step:7:1). Does this mean that just the `.solc` folder is missing (since I use compilation & Vyper) in that case and this the warning is issued?

**Comment by antazoey** [comment]
>  Does this mean that just the `.solc` folder is missing (since I use compilation & Vyper) in that case and thus the warning is issued?

I believe that is the case. Do you mind checking if the fix has resolved the warning for you?

**Comment by pcaversaccio** [comment]
> > Does this mean that just the `.solc` folder is missing (since I use compilation & Vyper) in that case and thus the warning is issued?
> 
> I believe that is the case. Do you mind checking if the fix has resolved the warning for you?

Is it already released? If yes, I can simply retrigger the latest CI run for snekmate.

**Comment by antazoey** [comment]
> Is it already released? If yes, I can simply retrigger the latest CI run for snekmate.

It is not released yet, but it's merged. I think you can use branches like this:

```
- uses: ApeWorX/github-action@main
```

But otherwise I noticed the WARNINGs are gone from the test runs of the action.

**Comment by pcaversaccio** [comment]
> > Is it already released? If yes, I can simply retrigger the latest CI run for snekmate.
> 
> It is not released yet, but it's merged. I think you can use branches like this:
> 
> ```
> - uses: ApeWorX/github-action@main
> ```
> 
> But otherwise I noticed the WARNINGs are gone from the test runs of the action.

I can confirm that the warnings are gone now:
![image](https://github.com/ApeWorX/github-action/assets/25297591/72b58457-bc8f-458a-b850-8f47c62d5f85)

https://github.com/pcaversaccio/snekmate/actions/runs/7766317138/job/21182002650
